### ISSUE TITLE
jupyter   Error：SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by loralyc** [yuantailing/ctw-baseline#14]
Hello,
when i try to follow the jupyter to run it ,it happens at the begining.how can i solve it?

  File "settings.py", line 1
    ../prepare/settings.py
    ^
SyntaxError: invalid syntax

should i move the settings.py or do something ?thanks!

**Comment by yuantailing** [comment]
It's a Linux symlink, not compatible with Windows.

**Comment by loralyc** [comment]
@yuantailing  but when i run it in linux, it also give me the same error

**Comment by yuantailing** [comment]
I think you could search `symbolic link' and resolve it by yourself.

**Comment by loralyc** [comment]
thank you very much, i already solve it.
