### ISSUE TITLE
OSError:[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by loralyc** [yuantailing/ctw-baseline#15]
hello, when i try to run the command cd ../detection && python3 eval.py, it tell me OSError
and i found the function 
                 def eval_yolo(split_id, tid):
     in eval.py  line 48
     settings.DARKNET_RESULTS_OUT is chinese,
     and os.path.dirname(settings.DARKNET_RESULTS_OUT means nothing 
     so it can't mkdir, do you know why ?

**Comment by yuantailing** [comment]
Oh, I made a mistake, I intend to ensure directory `settings.DARKNET_RESULTS_DIR` exists, it has been checked in `main()`, so just delete these two lines.

Thank you very mach, I will fix this in next commit.
