### ISSUE TITLE
when excute ../detection/merge_results.py     FileNotFoundError: [Errno 2] No such file or directory: 'products/results/chinese.0.txt'

### ISSUE THREAD

**Issue by haoyunjixiang** [yuantailing/ctw-baseline#18]
../dection/products/results/   have files like this:
chinese.00.txt
chinese.01.txt
chinese.02.txt
...........
chinese.01000.txt
FileNotFoundError: [Errno 2] No such file or directory: 'products/results/chinese.0.txt'
and in chinese.00.txt content like this:
0000238_0_0_6 0.005599 168.512253 18.311182 191.943985 73.990639
0000238_0_0_6 0.006422 154.573227 33.430981 174.645065 88.398880
0000238_0_0_6 0.006141 137.837555 49.250305 158.787659 104.747925
.....

so when i chage the filename another error is:
merge_results.py", line 44, in read_one
    file_path, cate_id, x, y, w, h, prob = line.split()
ValueError: not enough values to unpack (expected 7, got 6)

**Comment by yuantailing** [comment]
1. Why your filename is chinese.00.txt not chinese.0.txt? Did you modified the source code?
2. File content should be like this, your file content seems strange.

```
products/test/0000238_0_2_6.jpg 177 142.967026 224.330734 14.377014 17.517456 0.013882
products/test/0000238_0_2_6.jpg 376 142.967026 224.330734 14.377014 17.517456 0.587615
products/test/0000238_0_2_6.jpg 1000 142.967026 224.330734 14.377014 17.517456 0.074213
products/test/0000238_0_2_6.jpg 43 146.023880 224.456192 13.365021 17.498718 0.006112
products/test/0000238_0_2_6.jpg 376 146.023880 224.456192 13.365021 17.498718 0.101591
products/test/0000238_0_2_6.jpg 37 82.928383 212.396896 17.249283 22.279236 0.035544
```

**Comment by haoyunjixiang** [comment]
I didn't modified any source code,only modify the parameter in the settings.py.but I run the code in pycharm instead of jupyter notebook,I think it doesn't matter.

**Comment by haoyunjixiang** [comment]
I find the problem,I should download the darknet from ctw branch(which you modified).thank you very much. @yuantailing
