### ISSUE TITLE
Error on CodaLab （CTW dataset classification）

### ISSUE THREAD

**Issue by ChangjieWu** [yuantailing/ctw-baseline#27]
Hi, Yuan Tauiling.

When I submitted my result, something went wrong.
Do you know how to solve it?

Error:
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

**Comment by yuantailing** [comment]
We are sorry for such inconvenience.
The issue should have been resolved now, please try again.

**Comment by ChangjieWu** [comment]
Thank you very much for your work!
