### ISSUE TITLE
Dataset weiyun download link failed.

### ISSUE THREAD

**Issue by genausz** [yuantailing/ctw-baseline#28]
Dataset & Trained models download link (Weiyun) no longer valid.

https://share.weiyun.com/50hF1Cc

**Comment by yuantailing** [comment]
Oh, we will fix it as soon as possible.

**Comment by yuantailing** [comment]
It seems a bug of WeiYun. All my shared folders appear as empty. I have reported the bug to WeiYun.

**Comment by genausz** [comment]
> It seems a bug of WeiYun. All my shared folders appear as empty. I have reported the bug to WeiYun.

thanks for your help.

**Comment by genausz** [comment]
It's fixed. thanks.
