### ISSUE TITLE
Where to find annotation for text regions (text lines)? Only annotation for individual characters is found.

### ISSUE THREAD

**Issue by Banyueqin** [yuantailing/ctw-baseline#3]
您好，想问问为什么图片文字区域的标注只有单个文字的坐标标注，而没有一片文字区域的坐标标注，论文中是说有一片文字区域的坐标标注，不只有单个文字的坐标标注

**Comment by yuantailing** [comment]
A *text region (*text line* for most cases) is an array of character `instance`, please refer to `sentance` in `Annotation format` section in [tutorial/1-basics,ipynb](https://github.com/yuantailing/ctw-baseline/blob/master/tutorial/1-basics.ipynb).
