### ISSUE TITLE
Where can I locate the 'learning' module?

### ISSUE THREAD

**Issue by mrxiaohe** [yuantailing/ctw-baseline#33]
in the `train_image_classifier.py` file, there is a line that imports a module called `learning`. Is this a module that needs to be installed through `pip install` or is it a module provided by you? When I tried pip install `learning`, I was able to install it, but when I try `train.py`, it gave me an error message saying `learning` has no attribute `train`. Thanks!

**Comment by mrxiaohe** [comment]
Actually it just occurred to me that `learning.py` is in the `tf_hardcore` folder. For some reason, it's not recognized. I had to add the path to the folder to `sys.path`.

**Comment by yuantailing** [comment]
When you run *train.py* or *eval.py*, `.:tf_hardcode:slim` should have been added to `PYTHONPATH`, see:

https://github.com/yuantailing/ctw-baseline/blob/081c8361b0ed0675bf619ab6316ebf8415e93f46/classification/train.py#L15-L18

https://github.com/yuantailing/ctw-baseline/blob/081c8361b0ed0675bf619ab6316ebf8415e93f46/classification/train.py#L83

https://github.com/yuantailing/ctw-baseline/blob/081c8361b0ed0675bf619ab6316ebf8415e93f46/classification/train.py#L88
