### ISSUE TITLE
使用yolov3算法需要在哪些方面做出调整呢

### ISSUE THREAD

**Issue by peppapeppapeppapeppa** [yuantailing/ctw-baseline#37]
您好，抱歉打扰您，想请问一下您，使用yolov3算法需要做哪些做出调整呢？

**Comment by yuantailing** [comment]
我不是很清楚，可能直接用就行吧；把cfg换成YOLOv3的，重新训一遍。

**Comment by peppapeppapeppapeppa** [comment]
但是yolov3是darknet53,而您用的yolov2是darknet19，而且darknet是您修改过的版本，如果使用darknet53如何做出修改呢？

**Comment by yuantailing** [comment]
比较修改前后的 commit 是最准确的。一共 2 个 commit 改了几十行。

**Comment by peppapeppapeppapeppa** [comment]
谢谢您的耐心回答，还想请教您在anchor boxes的选取上采用了k-means聚类方法嘛？

**Comment by yuantailing** [comment]
没有
