### ISSUE TITLE
Aspect ratio of the anchor boxes

### ISSUE THREAD

**Issue by hope-yao** [yuantailing/ctw-baseline#41]
Hi Tailing,

Thank you for sharing the code and dataset! It is a great job!

I'm just writing to double-check if you performed KNN to find the optimum anchor box aspect ratio? Thanks!

**Comment by yuantailing** [comment]
There is no KNN. We use the default anchor settings provided by SSD and YOLOv2.

**Comment by hope-yao** [comment]
Thank you for clarifying!
