### ISSUE TITLE
How to detect characters from a certain image using trained models?

### ISSUE THREAD

**Issue by renwoxing2016** [yuantailing/ctw-baseline#7]
我正在看tutorial介绍及代码，希望能给与指导，利用已经训练的model，应该参考哪部分代码。

**Comment by yuantailing** [comment]
Refer to [tutorial 3-detection](https://github.com/yuantailing/ctw-baseline/blob/master/tutorial/3-detection.ipynb),

1. skip `Training steps' and download trained models to corresponding file path
1. replace detection testing set with your image(s)
1. run `Predicting steps'

**Comment by renwoxing2016** [comment]
because skip training steps, I run predicting steps, but report 'assert os.path.exists(obj)' of exists_and_newer funciton, I guess that it has not the file of 'cates.json'.  'cates.json' can be download?

**Comment by yuantailing** [comment]
See #8 ,run `python3 decide_cates.py` with TRAIN+VAL.

**Comment by yuantailing** [comment]
Thanks for your good issue, tutorial is now updated, a new tip has been added:

> If you are using trained models without training steps, you need to run `python3 decide_cates.py` (see *'Decide categories'* section) with TRAIN+VAL to generate `cates.json`, the map from label ID to character category.
